### ISSUE TITLE
Does the controller account for any existing entries in aws-auth cm?

### ISSUE THREAD

**Issue by srse369** [rustrial/aws-eks-iam-auth-controller#2]
Not sure if the controller reconciles only against iamidentitymapping custom resources. If so, it can potentially remove entries in aws-auth that grant access to the cluster.

**Comment by alex-berger** [comment]
As it is implemented today, the controller does only reconcile `iamidentitymapping` objects, and will overwrite (remove) all entries in `aws-auth` which have no corresponding `iamidentitymapping` object.

**Comment by alex-berger** [comment]
@ssetti I close this tickets as I answered your question. Please feel free to reopen/react if you need more information.

**Comment by sagikazarmark** [comment]
@alex-berger do you think it would make sense to add instructions to the readme for adding identitymapping objects for node roles? Feels like the instructions are incomplete without that since installing the controller as is will prevent new nodes from joining.

**Comment by alex-berger** [comment]
@sagikazarmark It would definitively make sense to add something like the sections below (with a bit of prosa text) to the readme. 

## `IAMIdentityMapping` for EC2 nodes 

```yaml
apiVersion: iamauthenticator.k8s.aws/v1alpha1
kind: IAMIdentityMapping
metadata:
  name: aws-ec2-nodes
spec:
  arn: 'arn:aws:iam::999999999999:role/your-ec2-node-role-name-here'
  groups:
    - 'system:bootstrappers'
    - 'system:nodes'
  username: 'system:node:{{EC2PrivateDNSName}}'
```

## `IAMIdentityMapping` for Fargate nodes

```yaml
apiVersion: iamauthenticator.k8s.aws/v1alpha1
kind: IAMIdentityMapping
metadata:
  name: aws-fargate-nodes
spec:
  arn: 'arn:aws:iam::999999999999:role/your-fargate-node-role-name-here'
  groups:
    - 'system:bootstrappers'
    - 'system:nodes'
    - 'system:node-proxier'
  username: 'system:node:{{SessionName}}'
```
